export const LOG_IN = 'LOG_IN';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const UPDATE_ANSWERED_QUESTIONS = 'UPDATE_ANSWERED_QUESTIONS';
export const UPDATE_UNANSWERED_QUESTIONS = 'UPDATE_UNANSWERED_QUESTIONS';
export const SAVE_QUESTION_ANSWER = 'SAVE_QUESTION_ANSWER'; 
export const SAVE_QUESTION = 'SAVE_QUESTION';

export const GET_USERS = 'GET_USERS';
